services:
  postgres:
    image: 'postgres:15'
    container_name: stockflow_postgres
    restart: always
    environment:
      POSTGRES_DB: stockflow_db
      POSTGRES_PASSWORD: stockfow_password
      POSTGRES_USER: stockflow_user
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
