spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5499/stockflow_db
spring.datasource.username=stockflow_user
spring.datasource.password=stockfow_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.orm.jdbc.bind=trace
